#!/usr/bin/env bash

# Use coreutils instead of MacOS's
export PATH="$(brew --prefix)/opt/coreutils/libexec/gnubin:${PATH}"

# Set FZF location for .vimrc
export FZF_ROOT="$(brew --prefix)/opt/fzf"

# Enable iTerm2 Shell Integration
if [ -n "$ZSH_VERSION" ]; then
  [ -f ../mac/iterm2_shell_integration.zsh ] && source ../mac/iterm2_shell_integration.zsh
elif [ -n "$BASH_VERSION" ]; then
  [ -f ../mac/iterm2_shell_integration.bash ] && source ../mac/iterm2_shell_integration.bash
else
  echo "iTerm2 Shell Integration for $SHELL can't be loaded"
fi
# https://stackoverflow.com/questions/9910966/how-to-tell-if-its-using-zsh-or-bash

# Install MacOS specific apps
# Chek if installed already (compare the checksums), if there is change, ask to install.
bash "${HOME}/.dotfiles/lib/run_when_changed" "${HOME}/.macos/install_muggle_apps"
bash "${HOME}/.dotfiles/lib/run_when_changed" "${HOME}/.macos/install_power_user_tools"
bash "${HOME}/.dotfiles/lib/run_when_changed" "${HOME}/.macos/install_android_tools"
