#!/usr/bin/env bash

# Use GNU utils
export PATH="$(brew --prefix)/opt/coreutils/libexec/gnubin:${PATH}"
export PATH="$(brew --prefix)/opt/ed/libexec/gnubin:${PATH}"
export PATH="$(brew --prefix)/opt/findutils/libexec/gnubin:${PATH}"
export PATH="$(brew --prefix)/opt/gawk/libexec/gnubin:${PATH}"
export PATH="$(brew --prefix)/opt/gnu-sed/libexec/gnubin:${PATH}"
export PATH="$(brew --prefix)/opt/gnu-tar/libexec/gnubin:${PATH}"
export PATH="$(brew --prefix)/opt/grep/libexec/gnubin:${PATH}"
export PATH="$(brew --prefix)/opt/make/libexec/gnubin:${PATH}"
# To see all the gnubin dirs there:
#   find "$(brew --prefix)/opt" -type d -follow -name gnubin -print
# Source: https://ryanparman.com/posts/2019/using-gnu-command-line-tools-in-macos-instead-of-freebsd-tools/

# Set FZF location for .vimrc
export FZF_ROOT="$(brew --prefix)/opt/fzf"

# Enable iTerm2 Shell Integration
if [ -z "$INTELLIJ_ENVIRONMENT_READER" ]; then
  # https://youtrack.jetbrains.com/articles/IDEA-A-19/Shell-Environment-Loading
  if [ -n "$ZSH_VERSION" ]; then
    [ -f ../mac/iterm2_shell_integration.zsh ] && source ../mac/iterm2_shell_integration.zsh
  elif [ -n "$BASH_VERSION" ]; then
    [ -f ../mac/iterm2_shell_integration.bash ] && source ../mac/iterm2_shell_integration.bash
  else
    echo "iTerm2 Shell Integration for $SHELL can't be loaded"
  fi
  # https://stackoverflow.com/questions/9910966/how-to-tell-if-its-using-zsh-or-bash
fi

# Install MacOS specific apps
# Check if installed already (compare the checksums), if there is change, ask to install.
if [ -z "$INTELLIJ_ENVIRONMENT_READER" ]; then
  # https://youtrack.jetbrains.com/articles/IDEA-A-19/Shell-Environment-Loading
  bash "${HOME}/.dotfiles/.lib/run_when_changed" "${HOME}/.macos/set_computer_name"
  bash "${HOME}/.dotfiles/.lib/run_when_changed" "${HOME}/.macos/install_xcode_cli"
  bash "${HOME}/.dotfiles/.lib/run_when_changed" "${HOME}/.macos/install_muggle_apps"
  bash "${HOME}/.dotfiles/.lib/run_when_changed" "${HOME}/.macos/install_power_user_tools"
  bash "${HOME}/.dotfiles/.lib/run_when_changed" "${HOME}/.macos/install_android_tools"
  bash "${HOME}/.dotfiles/.lib/run_when_changed" "${HOME}/.macos/set_system_preferences"
  bash "${HOME}/.dotfiles/.lib/run_when_changed" "${HOME}/.macos/set_system_preferences_misc"
  bash "${HOME}/.dotfiles/.lib/run_when_changed" "${HOME}/.macos/set_apple_apps_preferences"
  bash "${HOME}/.dotfiles/.lib/run_when_changed" "${HOME}/.macos/set_other_apps_preferences"
fi

# Homebrew
# to fix brew doctor warning "Homebrew's "sbin" was not found in your PATH"
export PATH="$(brew --prefix)/sbin:${PATH}"
