#!/usr/bin/env sh

# debug log
printf "reading: %s\t\t\t($0)\n" "bb_load" >> ~/.dotfiles_log

# Setup Babashka (bb) completion
if [ -n "$BASH_VERSION" ]; then
  [ -f "$HOME/.rc/bb.bash" ] && . "$HOME/.rc/bb.bash"
elif [ -n "$ZSH_VERSION" ]; then
  [ -f "$HOME/.rc/bb.zsh" ] && . "$HOME/.rc/bb.zsh"
fi
