#!/usr/bin/env sh

printf "reading: %s\t\t($0)\n" "aliases_android" >> ~/.dotfiles_log

# $1 - package name
adb_apk_pull() {
  local pkgname=$1
  mkdir -p "$pkgname"
  adb pull "$(adb shell pm path $pkgname | awk -F':' '{print $2}')" "${pkgname}/"
}
# Short:
#export NAME=com.amazon.kindle;  mkdir -p "$NAME"; adb pull "$(adb shell pm path $NAME | awk -F':' '{print $2}')" "${NAME}/"

alias adb_top_activity="adb shell dumpsys window windows | grep -E 'mCurrentFocus|mFocusedApp'"

adb_screencap() {
  local adb_cmd="${ADB_CMD:-"adb"}"
  NAME="screencap-$(date "+%Y%m%d_%H%M%S").png"
  $adb_cmd $@ shell mkdir -p /sdcard/DCIM/Screenshots/
  $adb_cmd $@ shell mkdir -p "/sdcard/DCIM/Screenshots"
  $adb_cmd $@ shell screencap "/sdcard/DCIM/Screenshots/${NAME}"
  $adb_cmd $@ pull "/sdcard/DCIM/Screenshots/${NAME}" .
}

adb_screenrecord() {
  local adb_cmd="${ADB_CMD:-"adb"}"
  NAME="screenrecord-$(date "+%Y%m%d_%H%M%S").mp4"
  $adb_cmd shell mkdir -p /sdcard/DCIM/Screenshots/
  echo "When finished call:\n    adb $@ pull /sdcard/DCIM/Screenshots/${NAME} .\n"
  $adb_cmd shell screenrecord --verbose --bit-rate 20000000 "/sdcard/DCIM/Screenshots/${NAME}"
}

adb_screenshare() {
  local adb_cmd="${ADB_CMD:-"adb"}"
  ADB="${adb_cmd}" scrcpy $@
}

adb_screenshare_all() {
  local adb_cmd="${ADB_CMD:-"adb"}"unloc
  for SN in `adb devices | tail -n +2 | awk '{print $1}'`; do
    ADB="${adb_cmd}" scrcpy -s ${SN} &
  done
}

adb_charles_proxy_start() {
  local sn=$1
  # open 8888 on device mapping my machine's 8888
  adb -s $sn reverse tcp:8888 tcp:8888
  # redirect traffic on device to device's 8888
  adb -s $sn shell settings put global http_proxy localhost:8888
}

adb_charles_proxy_stop() {
  local sn=$1
  adb -s $sn shell settings put global http_proxy :0
  adb -s $sn reverse --remove tcp:8888
}

adb_local_backend_start() {
  local sn=$1
  # open 3000 on device mapping my machine's 3000
  adb -s $sn reverse tcp:3000 tcp:3000
}

adb_local_backend_stop() {
  local sn=$1
  adb -s $sn reverse --remove tcp:3000
}

adb_app_clear() {
  local sn=$1
  local app=$2
  adb -s $sn shell pm clear $app
}

adb_app_stop() {
  local sn=$1
  local app=$2
  adb -s $sn shell am force-stop $app
}

alias adb_apk_list="adb shell pm list packages"

# TODO: Fix it. It's not going to work on Linux
#alias sdkmanager="JAVA_HOME=/Users/greg/.jenv/versions/1.8 sdkmanager"
