#!/usr/bin/env sh

# debug log
[ "${RC_DEBUG}" = true ] && printf "reading: %s\t\t($0)\n" "commonrc"
# includes
. "$HOME/.dotfiles/.lib/source_existing"

# Disable shell analytics, more: https://consoledonottrack.com
export DO_NOT_TRACK=1

# Add local bin paths to PATH
export PATH="${HOME}/.bin:${HOME}/.local/bin:${PATH}"

# Load aliases
source_existing "${HOME}/.aliases"

# Load platform specific setup
# (it needs to be done before the rest, some of the ENVs are set here)
source_existing "${HOME}/.platformrc"

# Load other configs if they exist

source_existing "$HOME/.rc/setup_android"

source_existing "$HOME/.rc/setup_autojump"

source_existing "$HOME/.rc/setup_babashka"

source_existing "$HOME/.rc/setup_fzf"

source_existing "$HOME/.rc/setup_gcp"

source_existing "$HOME/.rc/setup_go"

source_existing "$HOME/.rc/setup_gpg_ssh"

source_existing "$HOME/.rc/setup_jenv"

source_existing "$HOME/.rc/setup_nvm"

source_existing "$HOME/.rc/setup_python"
