#!/usr/bin/env sh

# debug log
printf "reading: %s\t\t\t($0)\n" "setup_pass_ryn"
# includes
. "$HOME/.dotfiles/.lib/pass_store"       # clone_pass_store

main() {
  clone_pass_store "git@github.com:rynkowsg/rynkowski-pass-store.git" "${HOME}/.password-store/rynkowski"
}

main "$@"
