#!/usr/bin/env bash

printf "reading: %s\t\t\t($0)\n" "setup_yarn" >> ~/.dotfiles_log

# Yarn scripts autocompletion
# Source: https://gist.github.com/ryaninvents/d9155214c91d18ddae3da021d3a13c99
zsh_yarn_autocompletion() {
    local scripts=$(jq -r '.scripts | to_entries | '\
'map(.key |= sub(":";"\\:";"g")) | '\
'.[] | '\
'[select((.value | length) > 0)] | '\
'select((. | length) > 0) | '\
'map("'"'"'\(.key):\(.value)'"'"'") | '\
'join(" ")' < package.json)
    _describe 'command' "($scripts)"
}

init_zsh_yarn_autocompletion() {
  compdef zsh_yarn_autocompletion yarn
}

if [ -n "$ZSH_VERSION" ]; then
  init_zsh_yarn_autocompletion
fi
