#!/usr/bin/env sh

# debug log
printf "reading: %s\t\t\t($0)\n" "fzf_common" >> ~/.dotfiles_log

fzf_load() {
  # shellcheck disable=SC2039
  if [ "$OSTYPE" = "darwin" ]; then
    export FZF_ROOT="/usr/local/opt/fzf"
  elif [ "$OSTYPE" = "linux-gnu" ]; then
    export FZF_ROOT="$HOME/.fzf"
  else
    printf "Error: %s\n" "fzf is not supported."
    exit 1;
  fi

  # Load fzf if exists
  if [ -d "${FZF_ROOT}" ]; then
    if [ -n "$BASH_VERSION" ]; then
      [ -f "$HOME"/.rc/fzf.bash ] && . "$HOME"/.rc/fzf.bash
    elif [ -n "$ZSH_VERSION" ]; then
      [ -f "$HOME"/.rc/fzf.zsh ] && . "$HOME"/.rc/fzf.zsh
    fi
  fi
}
