#!/usr/bin/env bash

# https://unix.stackexchange.com/a/152714
SCRIPT_DIR="$(cd "$(dirname "$([ -L "$0" ] && readlink "$0" || echo "$0")")" || exit 1; pwd -P)"
ROOT_DIR="$(cd "${SCRIPT_DIR}/../.." || exit 1; pwd -P)"

# install common apps/deps
sh "${ROOT_DIR}/.lib/macos/install_common"

###############################
###    ANDROID DEV TOOLS    ###
###############################

brew install gradle
brew install ktlint
brew install pidcat
brew install --cask android-sdk
brew install --cask vysor
brew install leakcanary-shark
brew install --cask chromedriver
