#!/usr/bin/env bash

set -x

# https://unix.stackexchange.com/a/152714
SCRIPT_DIR="$(cd "$(dirname "$([ -L "$0" ] && readlink "$0" || echo "$0")")" || exit 1; pwd -P)"
ROOT_DIR="$(cd "${SCRIPT_DIR}/../.." || exit 1; pwd -P)"

# install common apps/deps
sh "${ROOT_DIR}/.lib/macos/install_common"

# Web Browsers
brew install --cask firefox --appdir /Applications
brew install --cask google-chrome --appdir /Applications
brew install --cask tor-browser

# E-mail client
brew install --cask thunderbird

# Messengers
brew install --cask telegram-desktop
brew install --cask whatsapp
brew install --cask messenger
brew install --cask slack
brew install --cask signal
brew install --cask skype
brew install --cask zoom

# Office apps / editors / notepads
brew install --cask microsoft-office microsoft-auto-update
brew install --cask textmate
brew install --cask evernote
brew install --cask standard-notes

# Media
brew install --cask kindle
brew install --cask spotify
brew install --cask vlc
brew install media-info       # MediaInfo CLI
brew install --cask mediainfo # MediaInfo GUI

# Storage / cloud
#brew install --cask onedrive # its already included in microsoft-office

# Utils
brew install --cask 1password
# alternatively:
#     mas install 443987910   # 1Password
brew install --cask gimp
#brew install --cask inkscape
brew install --cask keka rar the-unarchiver
brew install --cask macs-fan-control
brew install --cask nordvpn
# alternatively:
#     mas install 1116599239  # NordVPN
brew install --cask techsmith-capture
brew install --cask transmission

# Optionally
# brew install --cask Geekbench # performance tests
