#!/usr/bin/env bash

set -x

# Spotify: Disable minimize start (when autostart enabled)
plutil -replace AutoStartSettingIsHidden -bool false "${HOME}/Library/Preferences/com.spotify.client.plist"
# Spotify: Disable autostart
sed -i 's|^\(app.autostart-mode=\).*$|\1"off"|' "${HOME}/Library/Application Support/Spotify/prefs"
# https://community.spotify.com/t5/Desktop-Mac/Auto-Startup-I-need-to-disable-it/td-p/4572478

# Spotify: Disable autoplay similar songs when your music ends
SPOTIFY_USER_PREFS="${HOME}/Library/Application Support/Spotify/Users/rynkowsg-user/prefs"
SPOTIFY_USER_PREFS_BACKUP="${SPOTIFY_USER_PREFS}.backup"
mkdir -p "$(dirname "${SPOTIFY_USER_PREFS}")"
touch "${SPOTIFY_USER_PREFS}"
cp "${SPOTIFY_USER_PREFS}" "${SPOTIFY_USER_PREFS_BACKUP}"
(
  grep -v app.player.autoplay "${SPOTIFY_USER_PREFS_BACKUP}"  \
    && echo "app.player.autoplay=false"
) | sort > "${SPOTIFY_USER_PREFS}"

# Alfred: Set folder for syncing preferences
ALFRED_PREFS="${HOME}/Library/Preferences/com.runningwithcrayons.Alfred-Preferences.plist"
# shellcheck disable=SC2088
plutil -replace syncfolder -string "~/OneDrive/Apps Data" "${ALFRED_PREFS}"

# TODO: sync TMUX settings
# https://apple.stackexchange.com/questions/111534/iterm2-doesnt-read-com-googlecode-iterm2-plist/111559#111559
# https://stackoverflow.com/questions/22943676/how-to-export-iterm2-profiles/27535485#27535485
