#!/usr/bin/env bash

# Applies finder settings.

set -x

###############################################################################
# Finder                                                                      #
###############################################################################

# Add a quit option to the Finder.
# Allows quitting via ⌘ + Q; doing so will also hide desktop icons
# https://macos-defaults.com/finder/QuitMenuItem.html
defaults write com.apple.finder QuitMenuItem -bool true

# Show hidden files by default
# https://macos-defaults.com/finder/AppleShowAllFiles.html
defaults write com.apple.finder AppleShowAllFiles -bool true

# Show all file extensions in the Finder.
# https://macos-defaults.com/finder/AppleShowAllExtensions.html
defaults write NSGlobalDomain AppleShowAllExtensions -bool true

# Disable the warning when changing a file extension
# https://macos-defaults.com/finder/FXEnableExtensionChangeWarning.html
defaults write com.apple.finder FXEnableExtensionChangeWarning -bool false

# Save to disk (not to iCloud) by default
# https://macos-defaults.com/finder/NSDocumentSaveNewDocumentsToCloud.html
defaults write NSGlobalDomain NSDocumentSaveNewDocumentsToCloud -bool false

# Remove the delay when hovering the toolbar title
# https://macos-defaults.com/finder/NSToolbarTitleViewRolloverDelay.html
defaults write NSGlobalDomain NSToolbarTitleViewRolloverDelay -float 0

# Set sidebar icon size to medium
# https://macos-defaults.com/finder/NSTableViewDefaultSizeMode.html
defaults write NSGlobalDomain NSTableViewDefaultSizeMode -int 2

# Disable window animations and Get Info animations
defaults write com.apple.finder DisableAllAnimations -bool true

# Set Desktop as the default location for new Finder windows
# For other paths, use `PfLo` and `file:///full/path/here/`
defaults write com.apple.finder NewWindowTarget -string "PfDe"
defaults write com.apple.finder NewWindowTargetPath -string "file://${HOME}/Desktop/"

# Show icons for hard drives, servers, and removable media on the desktop
defaults write com.apple.finder ShowExternalHardDrivesOnDesktop -bool true
defaults write com.apple.finder ShowHardDrivesOnDesktop -bool false
defaults write com.apple.finder ShowMountedServersOnDesktop -bool true
defaults write com.apple.finder ShowRemovableMediaOnDesktop -bool true

# Show status bar
defaults write com.apple.finder ShowStatusBar -bool true

# Show path bar
defaults write com.apple.finder ShowPathbar -bool true

# Display full POSIX path as Finder window title
defaults write com.apple.finder _FXShowPosixPathInTitle -bool true

# Keep folders on top when sorting by name
defaults write com.apple.finder _FXSortFoldersFirst -bool true

# When performing a search, search the current folder by default
defaults write com.apple.finder FXDefaultSearchScope -string "SCcf"

# Enable spring loading for directories
defaults write NSGlobalDomain com.apple.springing.enabled -bool true

# Remove the spring loading delay for directories
defaults write NSGlobalDomain com.apple.springing.delay -float 0

# Avoid creating .DS_Store files on network or USB volumes
defaults write com.apple.desktopservices DSDontWriteNetworkStores -bool true
defaults write com.apple.desktopservices DSDontWriteUSBStores -bool true

# Disable disk image verification
#defaults write com.apple.frameworks.diskimages skip-verify -bool true
#defaults write com.apple.frameworks.diskimages skip-verify-locked -bool true
#defaults write com.apple.frameworks.diskimages skip-verify-remote -bool true
# More:
# - https://forums.macrumors.com/threads/disable-dmg-verification-in-el-capitan-gm.1915693/

# Automatically open a new Finder window when a volume is mounted
defaults write com.apple.frameworks.diskimages auto-open-ro-root -bool true
defaults write com.apple.frameworks.diskimages auto-open-rw-root -bool true
defaults write com.apple.finder OpenWindowForNewRemovableDisk -bool true

# Show item info near icons on the desktop and in other icon views
/usr/libexec/PlistBuddy -c "Set :DesktopViewSettings:IconViewSettings:showItemInfo true" ~/Library/Preferences/com.apple.finder.plist
/usr/libexec/PlistBuddy -c "Set :FK_StandardViewSettings:IconViewSettings:showItemInfo true" ~/Library/Preferences/com.apple.finder.plist
/usr/libexec/PlistBuddy -c "Set :StandardViewSettings:IconViewSettings:showItemInfo true" ~/Library/Preferences/com.apple.finder.plist

# Show item info to the right of the icons on the desktop
/usr/libexec/PlistBuddy -c "Set DesktopViewSettings:IconViewSettings:labelOnBottom false" ~/Library/Preferences/com.apple.finder.plist

## Increase grid spacing for icons on the desktop and in other icon views
#/usr/libexec/PlistBuddy -c "Set :DesktopViewSettings:IconViewSettings:gridSpacing 100" ~/Library/Preferences/com.apple.finder.plist
#/usr/libexec/PlistBuddy -c "Set :FK_StandardViewSettings:IconViewSettings:gridSpacing 100" ~/Library/Preferences/com.apple.finder.plist
#/usr/libexec/PlistBuddy -c "Set :StandardViewSettings:IconViewSettings:gridSpacing 100" ~/Library/Preferences/com.apple.finder.plist
#
## Increase the size of icons on the desktop and in other icon views
#/usr/libexec/PlistBuddy -c "Set :DesktopViewSettings:IconViewSettings:iconSize 80" ~/Library/Preferences/com.apple.finder.plist
#/usr/libexec/PlistBuddy -c "Set :FK_StandardViewSettings:IconViewSettings:iconSize 80" ~/Library/Preferences/com.apple.finder.plist
#/usr/libexec/PlistBuddy -c "Set :StandardViewSettings:IconViewSettings:iconSize 80" ~/Library/Preferences/com.apple.finder.plist

# Use list view in all Finder windows by default
# Four-letter codes for the other view modes: `icnv`, `clmv`, `Flwv`
defaults write com.apple.finder FXPreferredViewStyle -string "Nlsv"

# Disable the warning before emptying the Trash
defaults write com.apple.finder WarnOnEmptyTrash -bool false

# Expand/collapse following File Info panes
defaults write com.apple.finder FXInfoPanesExpanded -dict \
	General -bool true \
	MetaData -bool true \
	OpenWith -bool true \
	Preview -bool false \
	Privileges -bool true

# Enable AirDrop over Ethernet and on unsupported Macs running Lion
defaults write com.apple.NetworkBrowser BrowseAllInterfaces -bool true

# Show the ~/Library folder
chflags nohidden ~/Library
# if exists, remove it
if xattr -p ~/Library | grep -q "com.apple.FinderInfo"; then
  xattr -d "com.apple.FinderInfo" ~/Library
fi
# To print flags:      ls -lO ~/
# To preview attr:     xattr -l ~/Library
# More: https://apple.stackexchange.com/a/378380

# Show the /Volumes folder
sudo chflags nohidden /Volumes

### Default apps

# $1 - app name
function id_of {
  echo "$(osascript -e "id of app \"${1}\"")"
}

textmate_id="$(id_of "TextMate")"
# texts / notes
duti -s "${textmate_id}" .adoc editor   # asciidoc
duti -s "${textmate_id}" .md editor     # markdown
duti -s "${textmate_id}" .txt editor
# shell scripts
duti -s "${textmate_id}" .bash editor
duti -s "${textmate_id}" .fish editor
duti -s "${textmate_id}" .sh editor
duti -s "${textmate_id}" .tcsh editor
duti -s "${textmate_id}" .zsh editor
# my dotfiles
duti -s "${textmate_id}" .bashrc editor
duti -s "${textmate_id}" .platformrc editor # my .dotfiles
duti -s "${textmate_id}" platformrc editor  # my .dotfiles
# data
duti -s "${textmate_id}" .csv editor
duti -s "${textmate_id}" .edn editor
duti -s "${textmate_id}" .json editor
duti -s "${textmate_id}" .xml editor
duti -s "${textmate_id}" .yml editor
# code
duti -s "${textmate_id}" .c editor
duti -s "${textmate_id}" .cc editor
duti -s "${textmate_id}" .cpp editor
duti -s "${textmate_id}" .clj editor
duti -s "${textmate_id}" .clj editor
duti -s "${textmate_id}" .cljc editor
duti -s "${textmate_id}" .cljs editor
duti -s "${textmate_id}" .h editor
duti -s "${textmate_id}" .hpp editor
duti -s "${textmate_id}" .java editor
duti -s "${textmate_id}" .js editor
duti -s "${textmate_id}" .jsx editor
duti -s "${textmate_id}" .kt editor
duti -s "${textmate_id}" .ts editor
duti -s "${textmate_id}" .tsx editor
# configs
duti -s "${textmate_id}" .conf editor
duti -s "${textmate_id}" .iml editor    # JetBrains config files
duti -s "${textmate_id}" .plist editor  # MacOS config files
# misc
duti -s "${textmate_id}" .asc editor    # armored GPG

preview_id="$(id_of "Preview")"
duti -s "${preview_id}" .pdf editor
duti -s "${preview_id}" .png viewer
duti -s "${preview_id}" .jpg viewer

vlc_id="$(id_of "VLC")"
# video
duti -s "${vlc_id}" .avi viewer
duti -s "${vlc_id}" .mkv viewer
duti -s "${vlc_id}" .mp4 viewer
# audio
duti -s "${vlc_id}" .acc viewer
duti -s "${vlc_id}" .m4a viewer
duti -s "${vlc_id}" .mp3 viewer
duti -s "${vlc_id}" .wav viewer

firefox_id="$(id_of "Firefox")"
duti -s "${firefox_id}" .html viewer

###############################################################################
# Photos                                                                      #
###############################################################################

# Prevent Photos from opening automatically when devices are plugged in
defaults -currentHost write com.apple.ImageCapture disableHotPlug -bool true

###############################################################################
# Other to consider                                                           #
###############################################################################

# Printer - Automatically quit printer app once the print jobs complete
defaults write com.apple.print.PrintingPrefs "Quit When Finished" -bool true

# Disable Game Center
defaults write com.apple.gamed Disabled -bool true

###############################################################################
# Kill affected applications                                                  #
###############################################################################

for app in \
	"Dock" \
	"Finder" \
	"Photos"; do
	killall "${app}" &> /dev/null || {
    RED="\e[0;91m"; RESET="\e[0m";
    printf "${RED}%s${RESET}\n" "Could not kill '${app}'."
  }
done
