#!/usr/bin/env bash

# debug log
printf "reading: %s\t\t($0)\n" "fzf.bash" >> ~/.dotfiles_log

#######################################################################
# These are files generated by fzf install (`${FZF_ROOT}/install`).   #
# The only change introduced are:
# - added header including log and this comment
# - replaced hardcoded path by $FZF_ROOT                              #
# #####################################################################

# Setup fzf
# ---------
if [[ ! "$PATH" == *${FZF_ROOT}/bin* ]]; then
  PATH="${PATH:+${PATH}:}${FZF_ROOT}/bin"
fi

# Auto-completion
# ---------------
[[ $- == *i* ]] && source "${FZF_ROOT}/shell/completion.bash" 2> /dev/null

# Key bindings
# ------------
source "${FZF_ROOT}/shell/key-bindings.bash"
