#!/usr/bin/env sh

printf "reading: %s\t\t($0)\n" "setup_python" >> ~/.dotfiles_log

# Load pyenv
# (based on instructions printed on `pyenv init`)
export PYENV_ROOT="$HOME/.pyenv"
export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init --path)"
eval "$(pyenv init -)"
# Load pyenv-virtualenv
if which pyenv-virtualenv-init > /dev/null; then
  eval "$(pyenv virtualenv-init -)";
fi
