#!/usr/bin/env bash

# paths initialization
SCRIPT_DIR="$(cd "$(dirname "$([ -L "$0" ] && readlink "$0" || echo "$0")")" || exit 1; pwd -P)"
ROOT_DIR="$(cd "${SCRIPT_DIR}/.." || exit 1; pwd -P)"
# includes
. "${ROOT_DIR}/.lib/error"

main() {
  set -e

  cd "$HOME/.dotfiles" || error_exit "Directory ~/.dotfiles does not exist."
  git pull --rebase

  local -r should_confirm=true
  "${ROOT_DIR}/.internal/install" "$should_confirm"
}

if [[ "${BASH_SOURCE[0]}" != "${0}" ]]; then
  [[ -n "${BASH_SOURCE[0]}" ]] && printf "%s\n\n" "Loaded: ${BASH_SOURCE[0]}"
else
  main "$@"
fi
