#!/usr/bin/env sh

# debug log
printf "reading: %s\t\t\t($0)\n" "aliases_linux"

alias clip-copy="xclip -sel clip"
alias clip-paste="xclip -o"

alias rpm-imported-keys="rpm -q gpg-pubkey --qf '%{NAME}-%{VERSION}-%{RELEASE}\t%{SUMMARY}\n'"
