#!/usr/bin/env bash

function install_homebrew {
  if ! command -v brew > /dev/null; then
#    /bin/bash -c "$(curl --location --fail --silent --show-error https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
  else
    RED='\033[0;31m'; NC='\033[0m' # No Color
    printf "${RED}%s${NC}\n" "Homebrew already installed"
  fi
}

function remove_homebrew {
  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/uninstall.sh)"
}
