#!/usr/bin/env sh

# debug log
printf "reading: %s\t\t\t($0)\n" "jenv_load" >> ~/.dotfiles_log
# imports
. ~/.dotfiles.envs                          # DOTFILES_BASE_PATH
. "${DOTFILES_BASE_PATH}/.lib/error"        # warning
. "${HOME}/.rc/jenv_common"                 # jenv_init, jenv_is_installed

init_jenv() {
  export PATH="${HOME}/.jenv/bin:${PATH}"
  eval "$(jenv init -)"
}

bash ~/.rc/jenv_setup

if jenv_is_installed; then
  jenv_init
else
  warning "jenv is not installed"
fi
