#!/usr/bin/env sh

# debug log
printf "reading: %s\t\t($0)\n" "jenv_load" >> ~/.dotfiles_log
# imports
. "$HOME/.dotfiles/.lib//error" # warning
. "$HOME/.rc/jenv_common"       # jenv_init, jenv_is_installed

init_jenv() {
  export PATH="${HOME}/.jenv/bin:${PATH}"
  eval "$(jenv init -)"
}

bash ~/.rc/jenv_setup

# Update (optionally)
CURRENT_JENV_VER="$(jenv --version | sed 's/^jenv \([0-9]*\.[0-9]*\.[0-9]*\)-.*$/\1/g')"
if jenv_is_installed; then
  jenv_init
else
  warning "jenv is not installed"
fi
