#!/usr/bin/env sh

printf "reading: %s\t\t($0)\n" "setup_jenv" >> ~/.dotfiles_log

JENV_DIR="$HOME/.jenv"

JENV_VER="0.5.5"
JENV_VER_TAG="v${JENV_VER}"
JENV_REPO="https://github.com/jenv/jenv.git"

install_jenv() {
  git -C "$HOME" -c advice.detachedHead=false clone --branch "$JENV_VER_TAG" --depth 1 "$JENV_REPO" "${JENV_DIR}"
}

# $1 - version
update_jenv() {
  cd "${JENV_DIR}"
  git fetch -t origin -- "$1"
  git checkout "$1" --
}

installed() {
  [ -f "$JENV_DIR/bin/jenv" ] && return 0 || return 1
}

init_jenv() {
  export PATH="${HOME}/.jenv/bin:${PATH}"
  eval "$(jenv init -)"
}

# if jenv still do not installed, skip reading the rest of this config
if ! installed; then
  return
fi

init_jenv

# Update (optionally)
CURRENT_JENV_VER="$(jenv --version | sed 's/^jenv \([0-9]*\.[0-9]*\.[0-9]*\)-.*$/\1/g')"
if installed && [ ! "$JENV_VER" = "$CURRENT_JENV_VER" ]; then
  warning "Current version ($CURRENT_JENV_VER) is different then expected ($JENV_VER)"
  yes_or_no "$(warning_color "Do you want to update it?")" && \
    update_jenv "$JENV_VER_TAG" &&                            \
    init_jenv
fi
