#!/usr/bin/env sh

# debug log
printf "reading: %s\t\t\t($0)\n" "setup_dotenv" >> ~/.dotfiles_log

# Setup dotenv
if [ -n "$ZSH_VERSION" ]; then
  [ -f "$HOME/.rc/dotenv.zsh" ] && . "$HOME/.rc/dotenv.zsh"
fi
