#!/usr/bin/env bash

# includes
. "$HOME/.dotfiles/.lib/error" # assert_command_exist
. "$HOME/.dotfiles/.lib/linux" # can_run_sudo

function install_dotfiles_deps_macos {
  # install Homebrew if not installed
  source "$HOME/.dotfiles/.lib/macos/homebrew"
  install_homebrew;
  brew install rcm pass
  brew install debianutils # provides: run-parts
  # install coreutils (usage of mktemp is different in GNU and BSD implementations)
  brew install coreutils
  export PATH="$(brew --prefix)/opt/coreutils/libexec/gnubin:${PATH}"
}

function install_dotfiles_deps_debian {
  if can_run_sudo; then
    sudo apt install rcm pass
  else
    assert_command_exist mkrc # package: rcm
    assert_command_exist pass
  fi
}

function install_dotfiles_deps_fedora {
  if can_run_sudo; then
    sudo dnf install rcm pass
    sudo dnf install crontabs # provides: run-parts
  else
    assert_command_exist mkrc # package: rcm
    assert_command_exist pass
    assert_command_exist run-parts # package: crontabs
  fi
}

function install_dotfiles_deps {
  RED='\033[0;31m'; NC='\033[0m' # No Color

  # on detecting system: https://stackoverflow.com/a/8597411
  if [[ "$OSTYPE" == "darwin"* ]]; then
    install_dotfiles_deps_macos
  elif [[ "$OSTYPE" == "linux-gnu"*  ]] && [ -f /etc/debian_version ]; then
    install_dotfiles_deps_debian
  elif [[ "$OSTYPE" == "linux-gnu"*  ]] && [ -f /etc/fedora-release ]; then
    install_dotfiles_deps_fedora
  elif [[ "$OSTYPE" == "linux-gnu"* ]]; then
    printf "${RED}%s${NC}\n" "This type of '${OSTYPE}' not supported."
    exit 1;
  else
    printf "${RED}%s${NC}\n" "'${OSTYPE}' not supported."
    exit 1;
  fi
}

function main {
  install_dotfiles_deps
}

# don't run main, if the script is imported using `source`
if [[ "${BASH_SOURCE[0]}" != "${0}" ]]; then
  [[ -n "${BASH_SOURCE[0]}" ]] && printf "%s\n\n" "Loaded: ${BASH_SOURCE[0]}"
else
  main "$@"
fi
