#!/usr/bin/env bash

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]:-${0}}")" || exit; pwd -P)"

# debug log
printf "reading: %s\t\t\t($0)\n" "pass_store"
# includes
. "$HOME/.dotfiles/.lib/error"
. "$HOME/.dotfiles/.lib/yes_or_no"

clone_pass_store() {
  local repo_url="$1"
  local store_dir="$2"
  if [ ! -d "${store_dir}" ]; then
    echo "${store_dir} is not installed"
    yes_or_no "Do you want to clone this repo?" || return
    mkdir -p "${store_dir}"
    git clone "${repo_url}" "${store_dir}"
  fi
}
