#!/usr/bin/env sh

# debug log
printf "reading: %s\t\t\t($0)\n" "source_utils"

source_existing() {
  [ -f "$1" ] && source "$1"
}

# Check whether file is sourced
# E.g: is_sourced && sourced=1 || sourced=0
# More: https://stackoverflow.com/a/28776166
is_sourced() {
 if [ -n "$ZSH_VERSION" ]; then
     case $ZSH_EVAL_CONTEXT in *:file:*) return 0;; esac
 else  # Add additional POSIX-compatible shell names here, if needed.
     case ${0##*/} in dash|-dash|bash|-bash|ksh|-ksh|sh|-sh) return 0;; esac
 fi
 return 1  # NOT sourced.
}

source_parts_safe() {
  local -r dir="$1"
  if [ -d "$dir" ]; then
    for f in `find "$dir" -type l`; do
      source "$f";
    done
  fi
}
