#!/usr/bin/env bash

#### UTILS: SCRIPT CLEANUP ####

declare -a on_exit_items

function on_exit() {
  for i in "${on_exit_items[@]}"; do
    eval $i
  done
}

function add_on_exit() {
  local -r n=${#on_exit_items[*]}
  on_exit_items[$n]="$*"
  # set the trap only the first time
  if [[ $n -eq 0 ]]; then
    trap on_exit EXIT
  fi
}
