#!/usr/bin/env sh

# debug log
printf "reading: %s\t\t\t($0)\n" "setup_babashka" >> ~/.dotfiles_log

# Setup Babashka (bb) completion
if [ -n "$BASH_VERSION" ]; then
  [ -f "$HOME/.bb.bash" ] && . "$HOME/.bb.bash"
elif [ -n "$ZSH_VERSION" ]; then
  [ -f "$HOME/.bb.zsh" ] && . "$HOME/.bb.zsh"
fi
