#!/usr/bin/env sh

# debug log
[ "${RC_DEBUG}" = true ] && printf "reading: %s\t\t($0)\n" "setup_babashka"

# Setup Babashka (bb) completion
if [ -n "$BASH_VERSION" ]; then
  [ -f "$HOME/.bb.bash" ] && . "$HOME/.bb.bash"
elif [ -n "$ZSH_VERSION" ]; then
  [ -f "$HOME/.bb.zsh" ] && . "$HOME/.bb.zsh"
fi
