#!/usr/bin/env sh

# debug log
[ "${RC_DEBUG}" = true ] && printf "reading: %s\t($0)\n" "setup_autojump"

# TODO: fix and compare with files on macos
#       On linux they are at /usr/share/autojump/

# https://github.com/wting/autojump
if [ -n "$BASH_VERSION" ] || [ -n "$ZSH_VERSION" ]; then
  [ -f "$(brew --prefix)/etc/profile.d/autojump.sh" ] && . "$(brew --prefix)/etc/profile.d/autojump.sh"
elif [ -n "$FISH_VERSION" ]; then
  [ -f "$(brew --prefix)/share/autojump/autojump.fish" ]; and source "$(brew --prefix)/share/autojump/autojump.fish"
fi
